name: Custom Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --channel=0 \
            --install "ndk;29.0.14206865"
          echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV

      - name: Build libhev
        run: |
          cd ${{ github.workspace }}
          bash compile-hevtun.sh

      - name: Copy libhev
        run: |
          cp -r ${{ github.workspace }}/libs ${{ github.workspace }}/V2rayNG/app/

      - name: Fetch AndroidLibXrayLite tag
        run: |
          pushd AndroidLibXrayLite
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
          popd

      - name: Download libv2ray
        uses: robinraju/release-downloader@v1.13
        with:
          repository: '2dust/AndroidLibXrayLite'
          tag: ${{ env.CURRENT_TAG }}
          fileName: 'libv2ray.aar'
          out-file-path: 'V2rayNG/app/libs'

      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore my-release-key.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias my-key-alias \
            -storepass mypassword123 \
            -keypass mypassword123 \
            -dname "CN=MyApp, OU=Dev, O=MyOrg, L=City, S=State, C=IR"

      - name: Build APK
        run: |
          cd V2rayNG
          chmod +x gradlew
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/my-release-key.jks \
            -Pandroid.injected.signing.store.password=mypassword123 \
            -Pandroid.injected.signing.key.alias=my-key-alias \
            -Pandroid.injected.signing.key.password=mypassword123

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: v2rayNG-release-apk
          path: V2rayNG/app/build/outputs/apk/release/*.apk

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore-keep-safe
          path: my-release-key.jks
